### PR TITLE
Read the input image instead of using remote URL.

### PR DESCRIPTION
**Pull request by markstur**
The returned JSON includes imageURL which we were using
to display the image as seen by the server. But we ran
into an installation where that URL was not accessible.
So this fix just reads the selected file for display.

Left a comment in the code for now to mention what we
used to do just in case.

Also updated npm dependencies.

Closes: #47

### CODE REVIEW

**Comment by stevemart** [comment]
How was it not accessible?

I was going to suggest you check if there server is still returning imageURL and if it doesn't then use your new reader approach. So you could satisfy both cases. But I'm not sure as "not accessible" means in your commit message

**Comment by markstur** [comment]
It might be a setup issue, but w/ the new SuperVessel install I access it via https and host URL below, but the imageUrl which is for the "temp" image on the server is http and different hostname. Even if it is fixable on SuperVessel it is probably something a customer could also configure like this.

My original thinking was to prefer that returned url in case of resizing. But now that I have the file reader working and no resizing issue it is easier to just rely on the image that was selected instead of re-fetching what was uploaded.  Should probably delete the comment about "FYI: the old way" but thought I'd let it sit just in case.

Example API URL and see the imageURL in the results:

Web API URL: https://ny1.ptopenlab.com/powerai-vision-ny/api/dlapis/24a05876-1696-431f-a6b4-9baaf85e5ddd
Server starting on 8081
{"webAPIId":"24a05876-1696-431f-a6b4-9baaf85e5ddd","imageUrl":"http://powerai-vision-ny-portal:9080/powerai-vision-ny-api/uploads/temp/24a05876-1696-431f-a6b4-9baaf85e5ddd/af8c970d-4dd3-47b0-8af9-abde33dbd929.png","imageMd5":"5c6390984dc9d16e50ad1d10c5cefede","classified":[{"confidence":

**Comment by markstur** [comment]
Oh and it would be nice if I could use a `if imageURL` for the condition (probably what you were thinking), but unfortunately I get one and it just will timeout instead of load.

**Comment by stevemart** [comment]
> unfortunately I get one and it just will timeout instead of load.

Ah, there's the rub. Go ahead and remove the older approach in another PR if you'd like.

**Pull request merged**
